### ISSUE TITLE
Où trouver les fichiers de langue

### ISSUE THREAD

**Issue by SirWrexes** [dofera/dofedex#11]
Hello !

Je me demandais où est-ce que vous trouviez les fichiers de langue ?

J'aimerais bien mettre la main sur une version à jour, mais ça fait des heures que je fouille dans `retroclient/` et que j'ouvre des `.swf` dans tous les sens avec JPEXS sans jamais trouver de truc qui ressemble aux fichiers de traduction disponibles ici.

Merci !

**Comment by SirWrexes** [comment]
Après avoir fouillé un peu sur des forums, j'ai trouvé ceci.
https://github.com/Dysta/PyLangGetter

**Comment by dofera** [comment]
https://github.com/dofera/getlang.sh
