### ISSUE TITLE
Deobfuscated loaders

### ISSUE THREAD

**Issue by Lu-Leandre** [dofera/dofedex#3]
Bonjour

Auriez vous la possibilité d'ajouter sur votre github la dernière version du loader deobfu ? 

ça serais vraiment géniale de votre part :D

en espérant que ça ne vous demanderas pas trop de travaille, j'ai aucune idée si c'est chronophage ce genres de projet ^^"

merci par avance et bonne continuation ;)

**Comment by dofera** [comment]
Bonjour, le projet de désobfuscation n'est plus actif pour le moment.
