### ISSUE TITLE
Parsing areas and map coordinates

### ISSUE THREAD

**Issue by yamoling** [dofera/dofedex#7]
Hello,

I am currently working on a project where I would like to some extra information about the maps such as their coordinates and their zone (Amakna, Bonta, Astrub, etc).
I could not find that information in the swf files although I suspect the area might match the 'musicId' field and that the coordonates are 'hidden' somewhere.

Do you think you could add that data to your maps? Or maybe you have an idea of where to find that information such I can then contribute to the project.

Best,

  Yannick (discord Yanneke#8776)

**Comment by Lounek09** [comment]
Hey, the coordinates and areas of each map are in the maps lang.

Check https://github.com/dofera/dofedex/blob/master/lang/fr/maps/maps_fr_1097.swf with https://github.com/jindrapetrik/jpexs-decompiler

I suggest you to download the latest version, the lang here are 4months old.

**Comment by yamoling** [comment]
Hello Lounek,
Thank you for your answer, I did find what I was looking for !
Could I push as far as to asking how you extract that information from the game files? I could not find documentation about that procedure on this git repo and the 'official' swf map files do not include that data as far as I can tell.
