### ISSUE TITLE
What are the URLs to download previous versions of Dofus retro

### ISSUE THREAD

**Issue by GuiWDev** [dofera/dofedex#9]
Hi,

First, thank you for this gold mine with all the current and past versions of Dofus 1.x, it's really impressive to see the very first versions of the game are there. This is very precious for enthusiasts of the game like me who also happen to be programmers and want to experiment with server emulation or game modding.

In an effort to check the versions are untampered and also out of curiosity, I tried to find how you managed to do that but I couldn't find the download links for the past versions.

For the current version, there is the endpoint https://launcher.cdn.ankama.com/cytrus.json and then we can get the list of files with https://launcher.cdn.ankama.com/retro/releases/main/windows/5.0_1.38.8.1815.148-6cfa3c9.json, but I can't find any index endpoint for past versions. So far, I also can't manage to work out the algorithm used to generate the name of the file above (`5.0_1.38.8.1815.148-6cfa3c9.json`):
* `5.0` seems hardcoded and likely the version of their tool Cytrus
* `1.38.8` is the version of the game
* `1815.148` is probably some build numbers
* `6cfa3c9` is probably a hash, but I don't know a hash of what

Could you please explain how to build the URLs for the past versions of the game? If you don't want the information to be public, would you consider sending it in private? My email is guiwdev@gmail.com

Thank you!

**Comment by dofera** [comment]
Hello @GuiWDev, thank you for your words.

For the current version, the cytrus is no longer in version 5, the new endpoint is https://cytrus.cdn.ankama.com/cytrus.json.
`6cfa3c9` looks like a commit hash. 

I don't know if you are talking about legacy or retro versions. I dug up the web for the former, and downloaded gradually for the latter. Please do not use any client in this repository for gaming purposes, as I cannot guarantee their safety.

I am now keeping track of cytrus versions at https://github.com/dofera/cytrus.
